del *.pdf
ps2pdf -dEmbedAllFonts#true -dSubsetFonts#true -dEPSCrop#true -dPDFSETTINGS#/prepress AL_solar_correlation.eps AL_solar_correlation.pdf
ps2pdf -dEmbedAllFonts#true -dSubsetFonts#true -dEPSCrop#true -dPDFSETTINGS#/prepress AR_autocorr.eps AR_autocorr.pdf
ps2pdf -dEmbedAllFonts#true -dSubsetFonts#true -dEPSCrop#true -dPDFSETTINGS#/prepress AR_cdf.eps AR_cdf.pdf
ps2pdf -dEmbedAllFonts#true -dSubsetFonts#true -dEPSCrop#true -dPDFSETTINGS#/prepress AR_corrcoff.eps AR_corrcoff.pdf
ps2pdf -dEmbedAllFonts#true -dSubsetFonts#true -dEPSCrop#true -dPDFSETTINGS#/prepress solar_autocorrelation.eps solar_autocorrelation.pdf
ps2pdf -dEmbedAllFonts#true -dSubsetFonts#true -dEPSCrop#true -dPDFSETTINGS#/prepress solar_ar_30_day_ahead.eps solar_ar_30_day_ahead.pdf
ps2pdf -dEmbedAllFonts#true -dSubsetFonts#true -dEPSCrop#true -dPDFSETTINGS#/prepress mean_abs_error.eps mean_abs_error.pdf
ps2pdf -dEmbedAllFonts#true -dSubsetFonts#true -dEPSCrop#true -dPDFSETTINGS#/prepress price_ar_30_day_ahead.eps price_ar_30_day_ahead.pdf
ps2pdf -dEmbedAllFonts#true -dSubsetFonts#true -dEPSCrop#true -dPDFSETTINGS#/prepress price_autocorr.eps price_autocorr.pdf
ps2pdf -dEmbedAllFonts#true -dSubsetFonts#true -dEPSCrop#true -dPDFSETTINGS#/prepress price_periodogram_sanjose.eps price_periodogram_sanjose.pdf
ps2pdf -dEmbedAllFonts#true -dSubsetFonts#true -dEPSCrop#true -dPDFSETTINGS#/prepress wind_autocorrelation.eps wind_autocorrelation.pdf
ps2pdf -dEmbedAllFonts#true -dSubsetFonts#true -dEPSCrop#true -dPDFSETTINGS#/prepress wind_periodogram_al.eps wind_periodogram_al.pdf 
ps2pdf -dEmbedAllFonts#true -dSubsetFonts#true -dEPSCrop#true -dPDFSETTINGS#/prepress solar_ar_1_day_space_corr.eps solar_ar_1_day_space_corr.pdf
ps2pdf -dEmbedAllFonts#true -dSubsetFonts#true -dEPSCrop#true -dPDFSETTINGS#/prepress solar_ar_30_day_space_corr.eps solar_ar_30_day_space_corr.pdf 
ps2pdf -dEmbedAllFonts#true -dSubsetFonts#true -dEPSCrop#true -dPDFSETTINGS#/prepress solar_ar_30_day_space_corr.eps solar_ar_30_day_space_corr.pdf 
ps2pdf -dEmbedAllFonts#true -dSubsetFonts#true -dEPSCrop#true -dPDFSETTINGS#/prepress wind_ar_1_day_ahead.eps wind_ar_1_day_ahead.pdf
ps2pdf -dEmbedAllFonts#true -dSubsetFonts#true -dEPSCrop#true -dPDFSETTINGS#/prepress wind_ar_30_day_ahead.eps wind_ar_30_day_ahead.pdf
ps2pdf -dEmbedAllFonts#true -dSubsetFonts#true -dEPSCrop#true -dPDFSETTINGS#/prepress solar_svm.eps solar_svm.pdf
ps2pdf -dEmbedAllFonts#true -dSubsetFonts#true -dEPSCrop#true -dPDFSETTINGS#/prepress wind_svm.eps wind_svm.pdf solar_ar_corr_coff_1
ps2pdf -dEmbedAllFonts#true -dSubsetFonts#true -dEPSCrop#true -dPDFSETTINGS#/prepress solar_ar_corr_coff_1.eps solar_ar_corr_coff_1.pdf
ps2pdf -dEmbedAllFonts#true -dSubsetFonts#true -dEPSCrop#true -dPDFSETTINGS#/prepress wind_ar_corr_coff_1.eps wind_ar_corr_coff_1.pdf
ps2pdf -dEmbedAllFonts#true -dSubsetFonts#true -dEPSCrop#true -dPDFSETTINGS#/prepress solar_ar_corr_coff_30.eps solar_ar_corr_coff_30.pdf
ps2pdf -dEmbedAllFonts#true -dSubsetFonts#true -dEPSCrop#true -dPDFSETTINGS#/prepress wind_ar_corr_coff_30.eps wind_ar_corr_coff_30.pdf
ps2pdf -dEmbedAllFonts#true -dSubsetFonts#true -dEPSCrop#true -dPDFSETTINGS#/prepress solar_svm_corr_coff.eps solar_svm_corr_coff.pdf
ps2pdf -dEmbedAllFonts#true -dSubsetFonts#true -dEPSCrop#true -dPDFSETTINGS#/prepress wind_svm_corr_coff.eps wind_svm_corr_coff.pdf 
ps2pdf -dEmbedAllFonts#true -dSubsetFonts#true -dEPSCrop#true -dPDFSETTINGS#/prepress corr_coff_solar_wind_ar_1.eps corr_coff_solar_wind_ar_1.pdf 
ps2pdf -dEmbedAllFonts#true -dSubsetFonts#true -dEPSCrop#true -dPDFSETTINGS#/prepress corr_coff_solar_wind_ar_30.eps corr_coff_solar_wind_ar_30.pdf 
ps2pdf -dEmbedAllFonts#true -dSubsetFonts#true -dEPSCrop#true -dPDFSETTINGS#/prepress corr_coff_solar_wind_svm.eps corr_coff_solar_wind_svm.pdf 
ps2pdf -dEmbedAllFonts#true -dSubsetFonts#true -dEPSCrop#true -dPDFSETTINGS#/prepress cost_vs_beta.eps cost_vs_beta.pdf 
ps2pdf -dEmbedAllFonts#true -dSubsetFonts#true -dEPSCrop#true -dPDFSETTINGS#/prepress delay_cost_vs_beta.eps delay_cost_vs_beta.pdf 
ps2pdf -dEmbedAllFonts#true -dSubsetFonts#true -dEPSCrop#true -dPDFSETTINGS#/prepress energy_cost_vs_beta.eps energy_cost_vs_beta.pdf 
ps2pdf -dEmbedAllFonts#true -dSubsetFonts#true -dEPSCrop#true -dPDFSETTINGS#/prepress solar_ar_1_day_ahead_pdf.eps solar_ar_1_day_ahead_pdf.pdf 
ps2pdf -dEmbedAllFonts#true -dSubsetFonts#true -dEPSCrop#true -dPDFSETTINGS#/prepress wind_ar_1_day_ahead_pdf.eps wind_ar_1_day_ahead_pdf.pdf 
ps2pdf -dEmbedAllFonts#true -dSubsetFonts#true -dEPSCrop#true -dPDFSETTINGS#/prepress price_ar_1_day_ahead_pdf.eps price_ar_1_day_ahead_pdf.pdf 
ps2pdf -dEmbedAllFonts#true -dSubsetFonts#true -dEPSCrop#true -dPDFSETTINGS#/prepress solar_ar_30_day_ahead_pdf.eps solar_ar_30_day_ahead_pdf.pdf 
ps2pdf -dEmbedAllFonts#true -dSubsetFonts#true -dEPSCrop#true -dPDFSETTINGS#/prepress wind_ar_30_day_ahead_pdf.eps wind_ar_30_day_ahead_pdf.pdf 
ps2pdf -dEmbedAllFonts#true -dSubsetFonts#true -dEPSCrop#true -dPDFSETTINGS#/prepress price_ar_30_day_ahead_pdf.eps price_ar_30_day_ahead_pdf.pdf 
ps2pdf -dEmbedAllFonts#true -dSubsetFonts#true -dEPSCrop#true -dPDFSETTINGS#/prepress solar_svm_pdf.eps solar_svm_pdf.pdf 
ps2pdf -dEmbedAllFonts#true -dSubsetFonts#true -dEPSCrop#true -dPDFSETTINGS#/prepress wind_svm_pdf.eps wind_svm_pdf.pdf 
ps2pdf -dEmbedAllFonts#true -dSubsetFonts#true -dEPSCrop#true -dPDFSETTINGS#/prepress solar_ar_adv.eps solar_ar_adv.pdf 
ps2pdf -dEmbedAllFonts#true -dSubsetFonts#true -dEPSCrop#true -dPDFSETTINGS#/prepress wind_ar_adv.eps wind_ar_adv.pdf 
ps2pdf -dEmbedAllFonts#true -dSubsetFonts#true -dEPSCrop#true -dPDFSETTINGS#/prepress price_ar_adv.eps price_ar_adv.pdf 
ps2pdf -dEmbedAllFonts#true -dSubsetFonts#true -dEPSCrop#true -dPDFSETTINGS#/prepress solar_ar_adv_pdf.eps solar_ar_adv_pdf.pdf 
ps2pdf -dEmbedAllFonts#true -dSubsetFonts#true -dEPSCrop#true -dPDFSETTINGS#/prepress wind_ar_adv_pdf.eps wind_ar_adv_pdf.pdf 
ps2pdf -dEmbedAllFonts#true -dSubsetFonts#true -dEPSCrop#true -dPDFSETTINGS#/prepress price_ar_adv_pdf.eps price_ar_adv_pdf.pdf  
ps2pdf -dEmbedAllFonts#true -dSubsetFonts#true -dEPSCrop#true -dPDFSETTINGS#/prepress cost_comparison.eps cost_comparison.pdf 
ps2pdf -dEmbedAllFonts#true -dSubsetFonts#true -dEPSCrop#true -dPDFSETTINGS#/prepress solar_ar_autocoff_30.eps solar_ar_autocoff_30.pdf 
ps2pdf -dEmbedAllFonts#true -dSubsetFonts#true -dEPSCrop#true -dPDFSETTINGS#/prepress wind_ar_autocoff_30.eps wind_ar_autocoff_30.pdf 
ps2pdf -dEmbedAllFonts#true -dSubsetFonts#true -dEPSCrop#true -dPDFSETTINGS#/prepress solar_std_al.eps solar_std_al.pdf 
ps2pdf -dEmbedAllFonts#true -dSubsetFonts#true -dEPSCrop#true -dPDFSETTINGS#/prepress wind_std_al.eps wind_std_al.pdf 
ps2pdf -dEmbedAllFonts#true -dSubsetFonts#true -dEPSCrop#true -dPDFSETTINGS#/prepress price_ar_corr_coff_30.eps price_ar_corr_coff_30.pdf  
ps2pdf -dEmbedAllFonts#true -dSubsetFonts#true -dEPSCrop#true -dPDFSETTINGS#/prepress price_periodogram.eps price_periodogram.pdf 
ps2pdf -dEmbedAllFonts#true -dSubsetFonts#true -dEPSCrop#true -dPDFSETTINGS#/prepress ar_monthly_error_solar.eps ar_monthly_error_solar.pdf 
ps2pdf -dEmbedAllFonts#true -dSubsetFonts#true -dEPSCrop#true -dPDFSETTINGS#/prepress ar_monthly_error_wind.eps ar_monthly_error_wind.pdf 
ps2pdf -dEmbedAllFonts#true -dSubsetFonts#true -dEPSCrop#true -dPDFSETTINGS#/prepress ar_monthly_error_price.eps ar_monthly_error_price.pdf 
ps2pdf -dEmbedAllFonts#true -dSubsetFonts#true -dEPSCrop#true -dPDFSETTINGS#/prepress ar_hourly_pdf_error_solar.eps ar_hourly_pdf_error_solar.pdf 
ps2pdf -dEmbedAllFonts#true -dSubsetFonts#true -dEPSCrop#true -dPDFSETTINGS#/prepress ar_hourly_pdf_error_wind.eps ar_hourly_pdf_error_wind.pdf 
ps2pdf -dEmbedAllFonts#true -dSubsetFonts#true -dEPSCrop#true -dPDFSETTINGS#/prepress ar_hourly_pdf_error_price.eps ar_hourly_pdf_error_price.pdf  
ps2pdf -dEmbedAllFonts#true -dSubsetFonts#true -dEPSCrop#true -dPDFSETTINGS#/prepress price_std.eps price_std.pdf 
ps2pdf -dEmbedAllFonts#true -dSubsetFonts#true -dEPSCrop#true -dPDFSETTINGS#/prepress workload_periodogram.eps workload_periodogram.pdf 
ps2pdf -dEmbedAllFonts#true -dSubsetFonts#true -dEPSCrop#true -dPDFSETTINGS#/prepress ar_hourly_pdf_error_workload.eps ar_hourly_pdf_error_workload.pdf workload_ar_corr_coff_1
ps2pdf -dEmbedAllFonts#true -dSubsetFonts#true -dEPSCrop#true -dPDFSETTINGS#/prepress workload_ar_corr_coff_1.eps workload_ar_corr_coff_1.pdf
ps2pdf -dEmbedAllFonts#true -dSubsetFonts#true -dEPSCrop#true -dPDFSETTINGS#/prepress ar_q_solar.eps ar_q_solar.pdf
ps2pdf -dEmbedAllFonts#true -dSubsetFonts#true -dEPSCrop#true -dPDFSETTINGS#/prepress ar_q_wind.eps ar_q_wind.pdf
ps2pdf -dEmbedAllFonts#true -dSubsetFonts#true -dEPSCrop#true -dPDFSETTINGS#/prepress ar_q_price.eps ar_q_price.pdf
ps2pdf -dEmbedAllFonts#true -dSubsetFonts#true -dEPSCrop#true -dPDFSETTINGS#/prepress grad_converge.eps grad_converge.pdf
ps2pdf -dEmbedAllFonts#true -dSubsetFonts#true -dEPSCrop#true -dPDFSETTINGS#/prepress obj_converge.eps obj_converge.pdf 
ps2pdf -dEmbedAllFonts#true -dSubsetFonts#true -dEPSCrop#true -dPDFSETTINGS#/prepress wind_impact.eps wind_impact.pdf 